# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Scott Davis | Front End Developer
email: sc@ttdavis.com
description: > # this means to ignore newlines until "baseurl:"
  Front End Developer / Person
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sco.ttdavis.com" # the base hostname & protocol for your site
twitter_username: scttdavs
github_username:  scttdavs

# Collections
collections:
  photos:
    output: true
    permalink: /photos/:title/

# Build settings
markdown: kramdown

# Pagination
pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Outputting
permalink: blog/:title

# Other
excerpt_separator: <!--more-->

gems:
  - jekyll-sitemap
  - jekyll-paginate-v2
